# The URL the site will be built for
base_url = "https://24h.pogscience.org"

title = "24h Vulga – La, le, les physique·s"
description = "Rejoins-nous pour 12h de lives ininterrompus ! Des labos du CNRS aux volcans du monde, de l’aviation à l’art, en passant par la science-fiction, la biologie, l’histoire… et bien d’autres ✨"

default_language = "fr_FR"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Logo utilisé pour l'intégration des liens sur les réseaux sociaux ou similaire (OpenGraph)
logo = "logos/logo.png"

[extra.header]
# Le logo affiché sur les pages, à gauche du contenu ou du texte introductif.
# path pour le chemin vers le fichier, alt pour son texte alternatif.
logo = { path = "24h/24h-vulga.svg", alt = "24 heures vulga" }

# Le début et la fin de l'événement.
# L'affichage s'adaptera automatiquement, en affichant les noms des mois
# sauf si c'est le même mois. Les années ne sont pas affichées.
begin = "2023-12-02"
end = "2023-12-03"

[extra.overlay_banner]
# Logo affiché à gauche, taille cible : 300 par 300px
logo = { path = "streamers/pogscience.png", alt = "Logo de PogScience, jeton blanc avec écrit POG, au pourtour vert inscrit PogScience en cercle, quatre fois." }

# Contenu de la bannière. Vous pouvez utiliser Markdown.
content = "**Suivez la chaîne PogScience** pour être prévenu·e au début des 24h Vulga ou de nos autres événements à venir !"

# Lien affiché. À l'heure actuelle, uniquement sous la forme d'un bouton avec le logo et les couleurs de Twitch.
link = { url = "https://twitch.tv/pogscience", label = "Suivre" }

[extra.footer]
# La bannière affichée au dessus des liens du pied de page. Si commenté/absent, pas de bannière.
banner = { path = "logos/banner.png", alt = "Bannière PogScience, avec le logo PogScience et des dragon de komodo à la gueule grande ouverte, mascotte représentant le Pog de Twitch." }  # TODO meilleur alt

# Liens affichés dans le pied de page.
#
# Contenu de chaque élément :
#   title = texte affiché du lien (Markdown inline supporté)
# Et l'un des deux :
#   path = chemin interne du lien (vers un fichier statique ou .md)
#   url = chemin externe du lien
links = [
    { title = "Mentions légales", path = "@/legal.md" },
    { title = "PogScience", url = "https://pogscience.org" },
    { title = "Dossier de presse", url = "https://neon.ly/GS-DPresse" },
    { title = "**Qui est en live ?**", url = "https://pogscience.durss.fr" },
]

# Réseaux sociaux affichés dans le pied de page.
#
# Contenu de chaque élément :
#   title = texte du lien (infobulle & libellé alternatif)
#   icon = icône affichée
# Et l'un des deux :
#   path = chemin interne du lien (vers un fichier statique ou .md)
#   url = chemin externe du lien
#
# Les icônes suivantes sont supportées de base.
#   discord    facebook  flickr    github
#   instagram  linkedin  mastodon  reddit
#   tiktok     twitch    twitter   x-twitter
#   youtube
# Vous pouvez également ajouter un fichier SVG dans le dossier static/logos/social/ et mettre le nom sans l'extension.
social_networks = [
    { title = "X (Twitter)", icon = "twitter", url = "https://twitter.com/PogScience" },
    { title = "Instagram", icon = "instagram", url = "https://www.instagram.com/pogscience" },
    { title = "LinkedIn", icon = "linkedin", url = "https://www.linkedin.com/company/pogscience/" },
    { title = "Twitch", icon = "twitch", url = "https://www.twitch.tv/pogscience" },
    { title = "Discord", icon = "discord", url = "https://discord.gg/QcDZxbYPpj" },
    { title = "GitHub (code source)", icon = "github", url = "https://github.com/PogScience/" },
]
