# The URL the site will be built for
base_url = "https://24h.pogscience.org"

title = "24h Vulga – La, le, les physique·s"
description = "Rejoins-nous pour 12h de lives ininterrompus ! Des labos du CNRS aux volcans du monde, de l’aviation à l’art, en passant par la science-fiction, la biologie, l’histoire… et bien d’autres ✨"

default_language = "fr_FR"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Logo utilisé pour l'intégration des liens sur les réseaux sociaux ou similaire (OpenGraph)
logo = "logos/logo.png"

[extra.header]
# Le logo affiché sur les pages, à gauche du contenu ou du texte introductif.
# path pour le chemin vers le fichier, alt pour son texte alternatif.
logo = { path = "24h/24h-vulga.svg", alt = "24 heures vulga" }

# Le début et la fin de l'événement.
# L'affichage s'adaptera automatiquement, en affichant les noms des mois
# sauf si c'est le même mois. Les années ne sont pas affichées.
begin = "2023-12-02"
end = "2023-12-03"

[extra.overlay_banner]
logo = { path = "streamers/pogscience.png", alt = "PogScience" }
content = "**Suivez la chaîne PogScience** pour être prévenu·e au début des 24h Vulga !"
link = { url = "https://twitch.tv/pogscience", label = "Suivre" }

